/////////////// -- Recipes Actions -- ///////////////

export const GET_ALEATORY_RECIPES = 'GET_ALEATORY_RECIPES';
export const GET_RECIPES_BY_INGREDIENTS = 'GET_RECIPES_BY_INGREDIENTS'
export const GET_SEARCH_PRODUCTS = 'GET_SEARCH_PRODUCTS'
export const DELETE_BLUR = 'DELETE_BLUR'
export const DISPLAY_NONE_BUTTON_BLUR = 'DISPLAY_NONE_BUTTON_BLUR'