/////////////// -- Recipes Actions -- ///////////////

export const GET_ALEATORY_RECIPES = 'GET_ALEATORY_RECIPES';
export const GET_RECIPES_BY_INGREDIENTS = 'GET_RECIPES_BY_INGREDIENTS'
export const DELETE_INGREDIENTS_AND_RECIPES = 'DELETE_INGREDIENTS_AND_RECIPES' 
export const GET_RECIPE_BY_INGREDIENTS = 'GET_RECIPE_BY_INGREDIENTS'
export const GET_SEARCH_PRODUCTS = 'GET_SEARCH_PRODUCTS'
export const DELETE_BLUR = 'DELETE_BLUR'
export const DISPLAY_NONE_BUTTON_BLUR = 'DISPLAY_NONE_BUTTON_BLUR'
export const GET_NUTRITIONAL_INFO = 'GET_NUTRITIONAL_INFO'


export const ADD_PERSONAL_SHOPPING_LIST = 'ADD_PERSONAL_SHOPPING_LIST'
export const CREATE_SHOPPING_LIST = 'CREATE_SHOPPING_LIST'
export const GET_ALL_SHOPPINT_LIST = 'GET_ALL_SHOPPINT_LIST'
export const MARKED_INGREDIENT_PERSONAL_SHOPPING_LIST = 'MARKED_INGREDIENT_PERSONAL_SHOPPING_LIST'